services:
  beatsync:
    build: .
    image: beatsync
    container_name: beatsync
    volumes:
      - ./media:/app/media
      - ./output:/app/output
      - ./config.json:/app/config.json:ro
      - ./config_punch.json:/app/config_punch.json:ro
      - ./config_breathe.json:/app/config_breathe.json:ro
    command: ["--config", "config.json"]
